2018-11-29 00:48:04,845 - INFO - Бот запускается
2018-11-29 00:48:43,812 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-29 00:51:45,145 - INFO - Бот запускается
2018-11-29 00:52:19,508 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-29 00:55:07,895 - INFO - Бот запускается
2018-11-29 00:55:21,100 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-29 01:00:53,649 - INFO - Бот запускается
2018-11-29 01:01:14,604 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-29 01:28:23,288 - INFO - Бот запускается
2018-11-29 01:29:26,583 - INFO - Вызван /start
2018-11-29 01:30:01,349 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-29 01:58:21,892 - INFO - Бот запускается
2018-11-29 01:58:31,143 - INFO - Вызван /start
2018-11-29 01:58:33,476 - INFO - Вызван /start
2018-11-29 01:58:49,486 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-30 00:20:28,464 - INFO - Бот запускается
2018-11-30 00:20:51,844 - INFO - Вызван /start
2018-11-30 00:21:05,675 - INFO - Вызван /start
2018-11-30 00:33:40,531 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-30 00:33:48,552 - INFO - Бот запускается
2018-11-30 00:42:17,881 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-30 00:45:49,916 - INFO - Бот запускается
2018-11-30 00:51:51,738 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-30 00:51:57,308 - INFO - Бот запускается
2018-11-30 00:52:03,139 - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\Дмитрий\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\Дмитрий\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "C:\projects\lesson1\firststansbot\bot.py", line 18, in talk_to_me
    logging.info("User: %s, Chat id: %s, Message: %s", update.message.chat.usename, update.message.chat.id, update.message.text)
AttributeError: 'Chat' object has no attribute 'usename'
2018-11-30 00:52:40,665 - INFO - Received signal 2 (SIGINT), stopping...
2018-11-30 00:52:44,377 - INFO - Бот запускается
2018-11-30 00:52:47,747 - INFO - User: Stanevich, Chat id: 30241142, Message: sdfsdf
2018-11-30 01:17:38,316 - INFO - Received signal 2 (SIGINT), stopping...
2018-12-15 16:10:57,393 - INFO - Бот запускается
2018-12-15 16:11:23,523 - INFO - User: Stanevich, Chat id: 30241142, Message: привет
2018-12-15 16:11:32,417 - INFO - Received signal 2 (SIGINT), stopping...
